In [1]:
#coding:utf-8
#两层简单神经网络（全连接）
import tensorflow as tf

In [2]:
#定义输入和参数
x = tf.constant([[0.7, 0.5]])
w1= tf.Variable(tf.random_normal([2, 3], stddev=1, seed=1))
w2= tf.Variable(tf.random_normal([3, 1], stddev=1, seed=1))
print(w1)
print(w2)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32_ref>
<tf.Variable 'Variable_1:0' shape=(3, 1) dtype=float32_ref>


In [3]:
#定义前向传播过程
a = tf.matmul(x, w1)
y = tf.matmul(a, w2)

In [15]:
#用会话计算结果
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    w1temp = w1.eval(session = sess)
    w2temp = w2.eval(session = sess)
    
    print("x:\n", x.eval(session = sess), x.shape)
    print("w1:\n",w1temp, w1temp.shape)
    print("a in tf3_3 is:\n",sess.run(a), a.shape)
    
    print("w2\n",w2temp.shape)
    print("y in tf3_3 is:\n",sess.run(y),y.shape)

x:
 [[0.7 0.5]] (1, 2)
w1:
 [[-0.8113182   1.4845988   0.06532937]
 [-2.4427042   0.0992484   0.5912243 ]] (2, 3)
a in tf3_3 is:
 [[-1.7892749   1.0888433   0.34134272]] (1, 3)
w2
 (3, 1)
y in tf3_3 is:
 [[3.0904665]] (1, 1)
